proj5_mine.x: myspell.cpp hashtable.hpp hashtable.h
	g++ -g -std=c++11 myspell.cpp -o proj5_mine.x

test1: 
	./proj5.x /usr/share/dict/words test1.txt output_test1_his.txt

test0: 
	./proj5_mine.x /usr/share/dict/words test0.txt output_test0.txt

clean:
	rm *.o
